# Generated by Django 3.1.7 on 2021-03-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=20, null=True)),
                ('last_name', models.CharField(default=None, max_length=20, null=True)),
                ('email', models.EmailField(default=None, max_length=20, null=True)),
                ('company_name', models.CharField(default=None, max_length=20, null=True)),
                ('phone', models.CharField(default=None, max_length=20, null=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
